import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { mkdirSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";
const OUT_DIR = "dist";

mkdirSync(OUT_DIR, { recursive: true });

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  // 把 manifest.json / styles.css 也作为 entry，配合 copy loader 直接产出到 dist，无需额外拷贝步骤
  // 用对象式指定 out name，避免 esbuild 因共同前缀把 main.js 输出到 dist/src/
  entryPoints: [
    { in: "src/main.ts", out: "main" },
    { in: "manifest.json", out: "manifest" },
    { in: "styles.css", out: "styles" },
  ],
  loader: {
    ".json": "copy",
    ".css": "copy",
  },
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "ES2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outdir: OUT_DIR,
  // entryNames 默认 [name]，src/main.ts → dist/main.js；manifest.json/styles.css 同名直出
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
